### PR TITLE
Changed #3 to retrieve the data with a grep call so parsenumpages.py isn...

### PR DESCRIPTION
**Pull request by kurtbartholomew**
Um.........is this how this works?

### CODE REVIEW

**Comment by zfisch** [comment]
yup! I'm gonna check it out and push it if it makes sense : )

**Comment by zfisch** [comment]
Ran `numpages=$(curl -I -u $token:x-oauth-basic https://api.github.com/orgs/$org/members | grep -oP '(?<=page=)\d(?=>; rel="last")')` and got a `(23) Failed writing body` error.

**Comment by kurtbartholomew** [comment]
So it looks like the issue seems to be with Mac OS X actually. I ran it again just to make sure and it worked just fine for me. Do you have any output for your error I can look at? I'm having a lot of trouble finding much documentation on that error except that it seems to involve Mac OS X, curl, and piping.

Also, can you echo numpages and just see if its blank or if it actually contains a number?

**Comment by zfisch** [comment]
comes up blank. 

```
Zacharys-MacBook-Air:peeps zackfischmann$ numpages=$(curl -I -u $token:x-oauth-basic https://api.github.com/orgs/$org/members | grep -oP '(?<=page=)\d(?=>; rel="last")')
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 29707    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
(23) Failed writing body
Zacharys-MacBook-Air:peeps zackfischmann$ echo $numpages

Zacharys-MacBook-Air:peeps zackfischmann$
```

**Pull request closed without merging**
