### PR TITLE
Only add members of organization not currently being followed

### PR DESCRIPTION
**Pull request by prakal**
Modified it to only add members of the organization that the user is not currently following. 
- Added a little code that ignores current user if user is member of organization. 
- Provided a little stat of how many users are being added. 
  - This might be a little buggy, need to test it more.
- Next on agenda is to have a better check if the script has already been run instead of asking the user.

### CODE REVIEW

**Comment by shockey** [comment]
Oh man, this is gonna conflict to hell and back with #6 😅

**Comment by prakal** [comment]
I just saw your pull request :S I should have refreshed my page first. 
Should I pull it down, and redo on your code?

**Comment by shockey** [comment]
I'm not quite sure what the correct thing to do here is- my guess is that @zfisch will be able to resolve the conflict after ~~pulling~~ merging one of our PRs more easily than redoing work- I could be wrong, though.

These are good improvements, by the way!

**Comment by prakal** [comment]
Thanks, @kyleshockey! I am pretty new to pull requests and such. This is a pretty neat way to get familiar.

**Comment by zfisch** [comment]
Agreed! This is great guys. I'm also super new to merge conflicts so this will be a good learning experience for all of us :)

**Comment by zfisch** [comment]
Hey @prakal, just opened this back up after a few months away. There's definitely some good stuff in here, but too much to merge in as is. I'm going to close this PR, but if you have any specific changes you would like to make to singular components of the program, feel free to submit PRs!

**Pull request closed without merging**
